export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";

export const UPDATE_TASKS_REQUEST = "UPDATE_TASKS_REQUEST";
export const UPDATE_TASKS_SUCCESS = "UPDATE_TASKS_SUCCESS";
export const UPDATE_TASKS_FAILURE = "UPDATE_TASKS_FAILURE";

export const CREATE_TASKS_REQUEST = "CREATE_TASKS_REQUEST";
export const CREATE_TASKS_SUCCESS = "CREATE_TASKS_SUCCESS";
export const CREATE_TASKS_FAILURE = "CREATE_TASKS_FAILURE";

export const SELECT_TASK = "SELECT_TASK";

